version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: master
  labels:
  - dependencies
  ignore:
  - dependency-name: flask-smorest
    versions:
    - "> 0.21.0, < 0.22"
  - dependency-name: pytest
    versions:
    - "> 5.4.2, < 5.5"
  - dependency-name: flask-smorest
    versions:
    - 0.27.0
    - 0.28.0
    - 0.29.0
  - dependency-name: environs
    versions:
    - 9.3.0
    - 9.3.1
  - dependency-name: marshmallow-sqlalchemy
    versions:
    - 0.24.2
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: flask-migrate
    versions:
    - 2.6.0
  - dependency-name: pytest-xdist
    versions:
    - 2.2.0
