"""Example model

Revision ID: 890dde61a907
Revises: 
Create Date: 2020-01-02 22:44:44.685011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "890dde61a907"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "examples",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("good", sa.Boolean(), server_default="TRUE", nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("examples")
    # ### end Alembic commands ###
