name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11-alpine
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: project

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt bandit black flake8 safety
    - name: Lint the code
      run: |
        black --check --diff .
        bandit -r -l -i -q migrations project cli.py wsgi.py
        flake8 --count .
        safety check --bare
    - name: Unit tests
      run: py.test
      env:
        TEST_DATABASE_URL: postgresql://postgres:password@localhost:5432/project
